name: Force Fail (demo)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail on purpose
        run: |
          echo "Failing this PR intentionally for the demo"
          exit 1